# Generated by Django 6.0.3 on 2026-06-11 11:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Galerie', '0001_initial'),
        ('oeuvres', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_command', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='En attente', max_length=20)),
                ('otp', models.CharField(blank=True, max_length=6, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('galerie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Galerie.galerie')),
                ('oeuvres', models.ManyToManyField(blank=True, to='oeuvres.oeuvre')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
