# Generated by Django 6.0.3 on 2026-06-13 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0004_alter_command_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='status',
            field=models.CharField(choices=[('En attente', 'En attente'), ('Confirmée', 'Confirmée'), ('Livrée', 'Livrée'), ('Livrée', 'Livrée'), ('Annulée', 'Annulée')], default='En attente', max_length=20),
        ),
    ]
