# Generated by Django 6.0.2 on 2026-05-13 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Galerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('localisation', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('surface_x', models.FloatField()),
                ('surface_y', models.FloatField()),
                ('decor', models.CharField(max_length=200)),
                ('tarif_mensuel', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nb_oeuvres_max', models.IntegerField()),
                ('duree_acces', models.CharField(max_length=100)),
                ('prix_visiteur', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='GalerieImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='galeries/images/')),
                ('galerie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Galerie.galerie')),
            ],
        ),
    ]
