# Generated by Django 6.0.3 on 2026-06-12 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Galerie', '0002_galerie_created_at_galerie_published_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='galerie',
            name='subscription_type',
            field=models.CharField(choices=[('atelier', 'Atelier'), ('galerie', 'Galerie'), ('musee', 'Musée')], default='galerie', max_length=20),
        ),
    ]
