# Generated by Django 6.0.3 on 2026-06-11 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryaccess',
            options={'ordering': ['-purchased_at'], 'verbose_name': 'Accès à la galerie', 'verbose_name_plural': 'Accès aux galeries'},
        ),
    ]
