# Generated by Django 6.0.3 on 2026-06-12 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Galerie', '0002_galerie_created_at_galerie_published_at_and_more'),
        ('commandes', '0002_alter_command_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='galerie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Galerie.galerie'),
        ),
    ]
