# Generated by Django 6.0.3 on 2026-06-14 22:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Nouvelle analyse', max_length=255)),
                ('mode', models.CharField(choices=[('general', 'Analyse générale'), ('style', 'Style & technique'), ('histoire', 'Contexte historique'), ('symbolisme', 'Symbolisme'), ('emotion', 'Émotion & ressenti'), ('comparaison', "Comparaison d'œuvres")], default='general', max_length=20)),
                ('artwork_description', models.TextField(blank=True)),
                ('artwork_image', models.ImageField(blank=True, null=True, upload_to='artworks/')),
                ('total_tokens', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ia_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conversation',
                'verbose_name_plural': 'Conversations',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'Utilisateur'), ('assistant', 'Assistant')], max_length=10)),
                ('content', models.TextField()),
                ('tokens_used', models.PositiveIntegerField(default=0)),
                ('model_used', models.CharField(blank=True, max_length=100)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ia.conversation')),
            ],
            options={
                'verbose_name': 'Message',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('art_period', models.CharField(blank=True, max_length=150)),
                ('art_movement', models.CharField(blank=True, max_length=150)),
                ('techniques', models.JSONField(default=list)),
                ('artists_mentioned', models.JSONField(default=list)),
                ('keywords', models.JSONField(default=list)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_result', to='ia.message')),
            ],
            options={
                'verbose_name': "Résultat d'analyse",
            },
        ),
    ]
