# Generated by Django 6.0.2 on 2026-05-13 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Galerie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oeuvre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_realisation', models.DateField()),
                ('technique', models.CharField(max_length=150)),
                ('dimensions', models.CharField(max_length=150)),
                ('statut', models.CharField(choices=[('Brouillon', 'Brouillon'), ('Publié', 'Publié'), ('Vendu', 'Vendu')], default='Publié', max_length=50)),
                ('nb_exemplaires', models.IntegerField(default=1)),
                ('tags', models.JSONField(default=list)),
                ('img', models.ImageField(blank=True, null=True, upload_to='oeuvres/images/')),
                ('galerie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oeuvres', to='Galerie.galerie')),
            ],
        ),
    ]
