# Generated by Django 6.0.3 on 2026-06-15 12:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raw_prompt', models.TextField(verbose_name='Prompt naturel')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('tool', models.CharField(blank=True, choices=[('send_email', 'Envoyer un email'), ('send_reminder', 'Envoyer un rappel'), ('generate_report', 'Générer un rapport'), ('post_notif', 'Envoyer une notification')], max_length=30)),
                ('tool_params', models.JSONField(default=dict, help_text='Paramètres extraits (to, subject, body...)')),
                ('cron_hour', models.PositiveSmallIntegerField(blank=True, help_text='0-23', null=True)),
                ('cron_minute', models.PositiveSmallIntegerField(default=0)),
                ('cron_day', models.CharField(default='*', help_text='* ou 1-7 (lundi=1)', max_length=20)),
                ('repeat', models.BooleanField(default=True, help_text='Répéter ou exécuter une seule fois')),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'En pause'), ('done', 'Terminée'), ('failed', 'Échouée')], default='active', max_length=10)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('run_count', models.PositiveIntegerField(default=0)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tâche planifiée',
                'verbose_name_plural': 'Tâches planifiées',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('success', models.BooleanField(default=False)),
                ('output', models.TextField(blank=True, help_text="Résultat ou message d'erreur")),
                ('run_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='mcp_engine.scheduledtask')),
            ],
            options={
                'verbose_name': 'Exécution',
                'ordering': ['-run_at'],
            },
        ),
    ]
