# Generated by Django 6.0.3 on 2026-06-13 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Galerie', '0003_galerie_subscription_type'),
        ('purchases', '0002_alter_galleryaccess_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryaccess',
            options={'ordering': ['-purchased_at']},
        ),
        migrations.AddField(
            model_name='galleryaccess',
            name='subscription_type',
            field=models.CharField(blank=True, choices=[('atelier', 'Atelier'), ('galerie', 'Galerie'), ('musee', 'Musée')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='galleryaccess',
            name='gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accesses', to='Galerie.galerie'),
        ),
    ]
